### ISSUE TITLE
Release as Standalone Executable and/or Docker Image?

### ISSUE THREAD

**Issue by pbnj** [DavidDeSloovere/giphy-cli#16]
I would love to be able to use this tool, but I don't work with `dotnet` and I don't want to install the toolchain just to install this one tool.

Would it be possible to compile and release this tool as a standalone executable? My understanding is that `dotnet` cli supports this via `$ dotnet build`, but I could be wrong.

Alternatively (additionally?), it would be nice if there is a docker image version of this tool, so that it's as simple as `$ docker  run <giphy-cli-image>`. Admittedly, there could be a lot of trade-offs going this route (e.g. no clipboard, no iterm integration for gif previews ...etc).

**Comment by DavidDeSloovere** [comment]
Great idea.

I don't really know how this could be distributed as standalone, because I'm using nuget.org currently.

Docker should be doable however.

**Comment by DavidDeSloovere** [comment]
finally got the docker image done
will probably also push to docker hub (now in ghcr.io)

**Comment by DavidDeSloovere** [comment]
It's available on docker hub

https://hub.docker.com/r/daviddesloovere/giphy-cli
