### ISSUE TITLE
Feature Request: Add option to auto-copy gif url to clipboard

### ISSUE THREAD

**Issue by BenjaBobs** [DavidDeSloovere/giphy-cli#3]
Maybe a syntax like `giphy "some search" -c`.

Awesome tool btw.

**Comment by DavidDeSloovere** [comment]
Great idea.
Did some quick googling and there doesn't seem to be easy access to clipboard in .net core however.
Do you know any open source libs for this?

**Comment by BenjaBobs** [comment]
I found this: https://github.com/SimonCropp/TextCopy
